### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by mvhulten** [derpycode/cgenie.muffin#105]
At the moment cGENIE is not free.  Is there a licence intended but missing?

**Comment by derpycode** [comment]
It ... is intended to be free and fully open source ...

I'll go fix that today (and also for my other codes and latex books).


/andy

**Comment by mvhulten** [comment]
Thanks, that's good to know!  I'm looking forward looking at the model in more detail when I find the time.

Adding a `COPYING` or `LICENSE` file containing your licence of choice in the root of the repository is probably enough.  Some people advice (e.g. at the FSF) that the copyright and licence be mentioned in the header of every source file.

**Comment by mvhulten** [comment]
Great, I see the Expat licence is applied.  This is fine (as it is free and GPL-compatible)!
